CIS_DYNAMODB_PERSON_TABLE: cis-stream-prod-and-idv-IdentityVaultUsers-LMGGZ2XE8K6F
CIS_LOGGING_OUTPUT: cloudwatch
CIS_LOGGING_LEVEL: DEBUG
CIS_CLOUDWATCH_LOG_GROUP: production
GSUITE_DRIVER_PREFIX: mozilliansorg
GSUITE_DRIVER_INTERACTIVE: False
GSUITE_DRIVER_ENVIRONMENT: production
GSUITE_DRIVER_CONFORMANCE: False
